apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: srikavyapendiala/reactjs-nodejs-postgres_frontend
          stdin: true
          ports:
            - containerPort: 3000
          env:
            - name: CONTAINER_NAME
              value: http://backend-service:8080


